# Uncomment the next line to define a global platform for your project
 platform :ios, '16.0'

target 'LapseClone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftGen'
  pod 'SwiftLint'

  target 'LapseCloneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LapseCloneUITests' do
    # Pods for testing
  end

end
